### ISSUE TITLE
Roles claims not getting generated with the full namespace schema to match the ClaimsIdentity.RoleClaimType value

### ISSUE THREAD

**Issue by TradeArcher2020** [IdentityManager/IdentityManager.MembershipReboot#2]
I've implemented MembershipReboot with Groups and am also using Thinktecture.IdentityManager to manage my users and roles.  I've noticed that when I create a role (say "administrators"), the claim type gets set to "role" instead of the default "http://schemas.microsoft.com/ws/2008/06/identity/claims/role".  It looks like this making my IsInRole method return false always.  

Did I configure MembershipReboot or IdentityManager wrong?  Or is the responsibility on me to create my roles in IdentityManager with the full schema prefix ("http://schemas.microsoft.com/ws/2008/06/identity/claims/role")?

**Comment by Trapulo** [comment]
I have same problem. I tried to read related ticket and wiki but didn't find today the way to solve! I need to change the role claim name to allow IsInRole....
